name: BIO

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_bio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate bio
        id: gen_bio
        run: python scripts/generate_bio.py # This script needs to be saved as generate_bio.py

      - name: BIO
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"bio\": \"${{ steps.gen_bio.outputs.bio_content }}\"}" \
            https://api.github.com/user
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

