name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v1
      - name: Setup NodeJs 17.x
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js 
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        with:
          OPEN_WEATHER_MAP_KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_USER_KEY: ${{ secrets.TWITTER_USER_KEY }}
          HUB_API_KEY: ${{ secrets.HUB_API_KEY }}
          OCR_API_KEY: ${{ secrets.OCR_API_KEY }}
          COORDINATES_URL: ${{ secrets.COORDINATES_URL }}
          COORDINATES_TOKEN: ${{ secrets.COORDINATES_TOKEN }}
          MUSTACHE_MAIN_DIR: ${{ secrets.MUSTACHE_MAIN_DIR }}
          GITHUB_TOKEN: ${{ secrets.HUB_API_KEY }}
        env:
          OPEN_WEATHER_MAP_KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_USER_KEY: ${{ secrets.TWITTER_USER_KEY }}
          HUB_API_KEY: ${{ secrets.HUB_API_KEY }}
          OCR_API_KEY: ${{ secrets.OCR_API_KEY }}
          COORDINATES_URL: ${{ secrets.COORDINATES_URL }}
          COORDINATES_TOKEN: ${{ secrets.COORDINATES_TOKEN }}
          MUSTACHE_MAIN_DIR: ${{ secrets.MUSTACHE_MAIN_DIR }}
          GITHUB_TOKEN: ${{ secrets.HUB_API_KEY }}
          BRANCH_NAME: 'main'