name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v1
      - name: Setup NodeJs 17.x
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Clean the cache
        run: curl https://ezefranca.herokuapp.com/cache
      - name: Hello computer
        run: curl https://ezefranca.com/readme.html
      - name: Sleep for 5 seconds, you are tired
        run: sleep 5s
      - name: Now Install the dependencies
        run: npm install
      - name: Speak computar
        run: echo I am a good computer!
      - name: Generate README file
        run: node index.js
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
