name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install feedparser python-dateutil requests

      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
        run: python scripts/update_readme.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "ezequiel.ifsp@gmail.com"
          git config --global user.name "Ezequiel Santos"
          git add README.md
          git commit -m "Updated README with latest blog posts and music" || exit 0
          git push
